<script setup lang="ts">
import '@/assets/style/acceuil.css'
</script>

<template>
  <div class="acceuil">
    <div class="head text-white h-screen w-full flex flex-col items-center gap-12 text-pop-up-top ">
      <h1 class="text-9xl p-4 rounded-md mt-36 ">Mon Portfolio</h1>
    </div>

    <section id="qui-suis-je"
      class="flex flex-row items-center h-screen justify-between p-4 gap-4 self-center text-white">
      <div class="flex flex-col items-center w-full">
        <img src="@/assets/img/nid77.jpg" alt="12" class="w-1/2 h-1/2 object-cover rounded-full mb-4" />
        <h2 class="text-5xl font-extrabold">Qui suis-je ?</h2>
      </div>
      <div>
        <p class="text-2xl">
          Je m'appelle Rayan et je suis actuellement un
          <strong>étudiant en 2éme année de BUT INFORMATIQUE.</strong> Je suis une personne
          curieuse des nouvelles avancées informatiques. Ce que j'aime faire, c'est des projets
          personnels ou en équipe qui me permet d'en apprendre plus dans le développement
          informatique.
        </p>
      </div>
    </section>

    <section id="projet" class="projets flex flex-col items-center text-center">
      <h1 class="text-4xl font-extrabold text-white text-center">Mes projets</h1>

      <section class="">
        <h2 class="text-2xl font-extrabold text-white">Jeux-Vidéo</h2>

        <div class="projet-body">
          <a href="https://nid77.itch.io/mind-connexion">
            <img src="@/assets/img/gmtk2021.png" alt="icon Mind Connexion" />
            <h3>GMTK2021 - Mind Connexion</h3>
          </a>

          <a href="https://paperyka.itch.io/dicehead">
            <img src="@/assets/img/dice-head.png" alt="icon dicehead" />
            <h3>GMTK2022 - Dicehead</h3>
          </a>

          <a href="https://paperyka.itch.io/re-process">
            <img src="@/assets/img/re-process.png" alt="icon re-process" />
            <h3>GMTK2023 - Re-Process</h3>
          </a>
        </div>
      </section>

      <section class="">
        <h2 class="text-2xl font-extrabold text-white">Personnel</h2>

        <div class="projet-body">
          <a href="#">
            <img src="@/assets/img/soniccolors2d.png" alt="image du projet" />
            <h3>Sonic Colors 2D Ultimate</h3>
          </a>

          <a href="#">
            <img src="@/assets/img/gestio.png" alt="image du projet" />
            <h3>Gestionnaire des Taches sur Go</h3>
          </a>
        </div>
      </section>

      <section class="">
        <h2 class="text-2xl font-extrabold text-white">Scolaire</h2>

        <div class="projet-body">
          <a href="#">
            <img src="@/assets/img/projet-BUT/logo12cm3.png" alt="image du projet" />
            <h3>12cm3</h3>
          </a>

          <a href="#">
            <img src="@/assets/img/projet-BUT/site-basket.png" alt="image du projet" />
            <h3>Site web Basket</h3>
          </a>

          <a href="#">
            <img src="@/assets/img/projet-BUT/myweather.png" alt="image du projet" />
            <h3>MyWeather</h3>
          </a>
        </div>
      </section>
    </section>

    <section id="contact"
      class="flex flex-col text-center border border-white-500 bg-[#16161a] p-6 gap-4 w-3/4 self-center">
      <h2 class="text-3xl text-white font-extrabold">Me Contacter</h2>

      <p>Pour me contacter, vous pouvez m'envoyer un email !</p>

      <p class=""><i class="fas fa-envelope"></i> Email : ray.tcontact@protonmail.com</p>
    </section>
  </div>
</template>

<style scoped>
.acceuil {
  display: flex;
  flex-direction: column;
  gap: 3rem;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-7-3 1:38:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }

  100% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
  }
}

@keyframes slide-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }

  100% {
    -webkit-transform: translateX(-100px);
    transform: translateX(-100px);
  }
}


.slide-left {
  -webkit-animation: slide-left 1s both;
  animation: slide-left 1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-7-3 1:42:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-pop-up-top
 * ----------------------------------------
 */
@-webkit-keyframes text-pop-up-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    text-shadow: none;
  }

  100% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    /* text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3); */
  }
}

@keyframes text-pop-up-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    text-shadow: none;
  }

  100% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    /* text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3); */
  }
}


.text-pop-up-top {
  -webkit-animation: text-pop-up-top 0.75s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: text-pop-up-top 0.75s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
</style>
